# Generated by Django 5.2 on 2025-05-14 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_watchlist_users_watchlist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='start_bid',
            new_name='amount',
        ),
    ]
