# Generated by Django 5.2.1 on 2025-05-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_comment_item_remove_bid_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='auction_images/'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(choices=[('smartphones', 'Smartphones'), ('tablets', 'Tablets'), ('laptops', 'Laptops'), ('desktops', 'Desktop Computers'), ('monitors', 'Monitors'), ('tvs', 'Televisions'), ('cameras', 'Cameras'), ('audio', 'Audio Equipment'), ('gaming', 'Gaming Consoles'), ('accessories', 'Accessories'), ('wearables', 'Wearable Technology'), ('networking', 'Networking Equipment'), ('storage', 'Storage Devices'), ('components', 'Computer Components'), ('other', 'Other Electronics')], default='other', max_length=64),
        ),
        migrations.AlterField(
            model_name='auction',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
